# -*- coding: utf-8 -*-
"""Multipart Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ERaPt5ZLwFsM_6iLpP6GOR-QCZ-tGPK
"""

import json
import random
import time
import uuid
from datetime import datetime

"""### Telemetry Helper"""

class Telemetry:

    def __init__(self, total_steps):
        self.trace_id = str(uuid.uuid4())

        self.total_steps = total_steps
        self.completed_steps = 0

        self.run_start_time = time.time()

        self.agent_start_times = {}

        self.completed_agents = 0

    def current_timestamp(self):
        return datetime.utcnow().isoformat() + "Z"

    def pipeline_percent_complete(self):
        return round(
            (self.completed_steps / self.total_steps) * 100,
            2
        )

    def throughput(self):
        elapsed = max(
            time.time() - self.run_start_time,
            0.001
        )

        return round(
            self.completed_steps / elapsed,
            2
        )

    def emit(self, payload):
        print(json.dumps(payload))

"""###  Agent"""

class Agent:

    def __init__(
            self,
            name,
            steps,
            fail_at_step=None):

        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step

    def run(self, telemetry):

        span_id = str(uuid.uuid4())

        telemetry.agent_start_times[self.name] = time.time()

        # agent_started

        telemetry.emit({
            "timestamp": telemetry.current_timestamp(),
            "trace_id": telemetry.trace_id,
            "span_id": span_id,
            "event": "agent_started",
            "agent": self.name,
            "total_steps": self.steps
        })

        # Progress checkpoints
        checkpoints = set()

        checkpoints.add(max(1, round(self.steps * 0.25)))
        checkpoints.add(max(1, round(self.steps * 0.50)))
        checkpoints.add(max(1, round(self.steps * 0.75)))
        checkpoints.add(self.steps)

        # Agent Work

        for step in range(1, self.steps + 1):

            time.sleep(
                random.uniform(0.05, 0.20)
            )

            if (
                self.fail_at_step is not None
                and step == self.fail_at_step
            ):
                raise RuntimeError(
                    f"{self.name} failed at step {step}"
                )

            telemetry.completed_steps += 1

            if step in checkpoints:

                agent_progress = round(
                    (step / self.steps) * 100,
                    2
                )

                telemetry.emit({
                    "timestamp":
                        telemetry.current_timestamp(),

                    "trace_id":
                        telemetry.trace_id,

                    "span_id":
                        span_id,

                    "event":
                        "agent_progress",

                    "agent":
                        self.name,

                    "agent_percent_complete":
                        agent_progress,

                    "pipeline_percent_complete":
                        telemetry.pipeline_percent_complete(),

                    "throughput_steps_per_sec":
                        telemetry.throughput()
                })

        # agent_completed

        duration = round(
            time.time()
            - telemetry.agent_start_times[self.name],
            2
        )

        telemetry.completed_agents += 1

        telemetry.emit({
            "timestamp":
                telemetry.current_timestamp(),

            "trace_id":
                telemetry.trace_id,

            "span_id":
                span_id,

            "event":
                "agent_completed",

            "agent":
                self.name,

            "duration_seconds":
                duration,

            "pipeline_percent_complete":
                telemetry.pipeline_percent_complete(),

            "throughput_steps_per_sec":
                telemetry.throughput()
        })

"""### Orchestrator"""

class Orchestrator:

    def __init__(self, agents):

        self.agents = agents

        total_steps = sum(
            agent.steps
            for agent in agents
        )

        self.telemetry = Telemetry(total_steps)

    def run(self):

        failed_agent = None
        status = "success"

        try:

            for agent in self.agents:
                agent.run(self.telemetry)

        except Exception as ex:

            status = "failed"
            failed_agent = agent.name

            self.telemetry.emit({

                "timestamp":
                    self.telemetry.current_timestamp(),

                "trace_id":
                    self.telemetry.trace_id,

                "span_id":
                    str(uuid.uuid4()),

                "event":
                    "agent_failed",

                "agent":
                    agent.name,

                "error":
                    str(ex),

                "pipeline_percent_complete":
                    self.telemetry.pipeline_percent_complete(),

                "throughput_steps_per_sec":
                    self.telemetry.throughput()
            })

        finally:

            total_duration = round(
                time.time()
                - self.telemetry.run_start_time,
                2
            )

            self.telemetry.emit({

                "timestamp":
                    self.telemetry.current_timestamp(),

                "trace_id":
                    self.telemetry.trace_id,

                "span_id":
                    None,

                "event":
                    "run_summary",

                "status":
                    status,

                "duration_seconds":
                    total_duration,

                "agents_completed":
                    self.telemetry.completed_agents,

                "failed_agent":
                    failed_agent,

                "pipeline_percent_complete":
                    self.telemetry.pipeline_percent_complete(),

                "throughput_steps_per_sec":
                    self.telemetry.throughput()
            })

"""### Main"""

def main():

    agents = [

        Agent("Planner", 3),

        Agent("Researcher", 6),

        Agent("Writer", 4),

        Agent("Reviewer", 2)

    ]

    Orchestrator(agents).run()


if __name__ == "__main__":
    main()