# -*- coding: utf-8 -*-
"""Multi Agent Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4kFYc1wix8896amGym6fDeHPQRwx9sK
"""

!pip install azure-ai-inference

"""##Initializing AzureAI"""

import os
from openai import AzureOpenAI
from google.colab import userdata
from azure.ai.inference.models import SystemMessage, UserMessage

endpoint = userdata.get("AZURE_OPENAI_ENDPOINT")
model_name = "gpt-4o-mini"
deployment = "gpt-4o-mini"

subscription_key = userdata.get("AZURE_OPENAI_KEY")
api_version = "2024-12-01-preview"

client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=subscription_key,
)
SysMessage = f"You are a helpful assistant."
UsMessage = f"Hello, Who are you!"
response = client.chat.completions.create(
    messages=[
        SystemMessage(content=SysMessage),
        UserMessage(content=UsMessage)
    ],
    max_tokens=2000,
    temperature=1.0,
    top_p=1.0,
    model=deployment
)

print(response.choices[0].message.content)

"""##Generic Agent Function"""

def run_agent(system_prompt, user_input):

    response = client.chat.completions.create(
        model=deployment,
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_input
            }
        ],
        temperature=0.3
    )

    return response.choices[0].message.content

"""##Research Agent

Responsible for gathering information.
"""

def research_agent(query):

    prompt = """
    You are a Research Agent.

    Responsibilities:
    - Gather key facts
    - Explain concepts
    - Identify important points
    - Produce structured notes
    """

    return run_agent(prompt, query)

"""##Analysis Agent

Responsible for reasoning.
"""

def analysis_agent(research_notes):

    prompt = """
    You are an Analysis Agent.

    Responsibilities:
    - Analyze the research
    - Compare alternatives
    - Identify pros and cons
    - Generate insights
    """

    return run_agent(prompt, research_notes)

"""##Writer Agent

Responsible for formatting.
"""

def writer_agent(analysis):

    prompt = """
    You are a Technical Writer.

    Responsibilities:
    - Create a clean final response
    - Use headings and bullet points
    - Make the content easy to understand
    """

    return run_agent(prompt, analysis)

"""##Supervisor Agent

Orchestrates all agents.
"""

def supervisor_agent(query):

    print("Running Research Agent...")

    research = research_agent(query)

    print("Running Analysis Agent...")

    analysis = analysis_agent(research)

    print("Running Writer Agent...")

    final_output = writer_agent(analysis)

    return final_output

"""##Workflow"""

question = """
Explain Multi-Agent AI Systems and compare them with single-agent systems.
"""

result = supervisor_agent(question)

print(result)