# -*- coding: utf-8 -*-
"""Hallucination Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3zeeU1qY2lUwHmlVQAXNENG0FtP6hTX

##Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers torch sentence-transformers bert-score
# !pip install openai
# !pip install requests

"""##1. BERTScore

###Bidirectional Encoder Representations from Transformers

Compares generated text with a gold/reference answer.
"""

from bert_score import score

candidate = """
Paris is the capital of France and has a population of 50 million.
"""

reference = """
Paris is the capital city of France. Its population is approximately 2.1 million.
"""

P, R, F1 = score(
    [candidate],
    [reference],
    model_type="distilbert-base-uncased",
    lang="en"
)

print(f"BERTScore F1: {F1.mean().item():.4f}")

"""Interpretation

| Score     | Meaning                 |
| --------- | ----------------------- |
| >0.90     | Very similar            |
| 0.80–0.90 | Mostly correct          |
| <0.80     | Potential hallucination |

##2. SelfCheckGPT

Generate multiple answers and measure agreement.
"""

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

responses = [
    "Paris is the capital of France.",
    "The capital of France is Paris.",
    "France's capital city is Paris.",
    "Paris serves as France's capital."
]

embeddings = model.encode(responses)

sims = []

for i in range(len(embeddings)):
    for j in range(i+1, len(embeddings)):
        sims.append(
            cosine_similarity(
                [embeddings[i]],
                [embeddings[j]]
            )[0][0]
        )

consistency_score = np.mean(sims)

print(f"Consistency Score: {consistency_score:.4f}")

"""Interpretation

0.90+  => very consistent

0.75-0.90 => moderate confidence

<0.75 => likely hallucination

##3. FactScore-Style Verification

Extract claims and verify against retrieved evidence.
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

claim = "Paris has a population of 50 million."

evidence = """
Paris is the capital of France.
Its population is approximately 2.1 million.
"""

claim_emb = model.encode(claim, convert_to_tensor=True)
evidence_emb = model.encode(evidence, convert_to_tensor=True)

score = util.cos_sim(claim_emb, evidence_emb)

print("FactScore-like similarity:",
      score.item())

"""Typical Interpretation

| FactScore   | Interpretation                         |
| ----------- | -------------------------------------- |
| 0.90 – 1.00 | Excellent factual grounding            |
| 0.75 – 0.90 | Mostly factual, few unsupported claims |
| 0.50 – 0.75 | Significant factual issues             |
| < 0.50      | Many hallucinations                    |
| 0.00        | Completely unsupported                 |

##4. HHEM (Vectara)

Vectara publishes hallucination-evaluation models on HuggingFace.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install sentencepiece tiktoken

"""###Resolving Error Due to Version Issue"""

import transformers
import tokenizers
import sentencepiece

print(transformers.__version__)
print(tokenizers.__version__)

import transformers
print(transformers.__file__)
print(transformers.__version__)

!pip uninstall -y transformers tokenizers

!pip install transformers==4.46.3
!pip install tokenizers==0.20.3
!pip install sentencepiece

"""###Actual Implementation"""

from transformers import AutoConfig

cfg = AutoConfig.from_pretrained(
    "vectara/hallucination_evaluation_model",
    trust_remote_code=True
)

print(cfg)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "vectara/hallucination_evaluation_model",
    trust_remote_code=True
)

print(type(model))

print(dir(model))

import inspect

print(inspect.signature(model.predict))

result = model.predict([
    (
        "Paris is the capital of France.",
        "Paris is the capital of France."
    )
])

print(result)

result = model.predict([
    (
        "Paris is the capital of France.",
        "Tokyo is the capital of France."
    )
])

print(result)