# -*- coding: utf-8 -*-
"""AutoGen Studio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1od39PhGw_ywsVKfzNOGRi_nabPI1EISC
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q autogenstudio pyngrok

!autogenstudio version

import os
import getpass
from google.colab import userdata

if "GROQ_API_KEY" not in os.environ:
  os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
if "NGROK_TOKEN" not in os.environ:
  os.environ["NGROK_TOKEN"] = userdata.get("NGROK_TOKEN")
print(f"GROQ API Key is Available {os.environ["GROQ_API_KEY"][:4]}")
print(f"NGROK Token is Available {os.environ["NGROK_TOKEN"][:4]}")

!ngrok config add-authtoken {os.environ["NGROK_TOKEN"]}

import multiprocessing
import time
from pyngrok import ngrok

def run_autogen_studio():
    # Launch AutoGen Studio on port 8081
    !autogenstudio ui --port 8081 --host 0.0.0.0

# Start AutoGen Studio in a background process
process = multiprocessing.Process(target=run_autogen_studio)
process.start()

# Wait a moment for the server to spin up
time.sleep(5)

# Open the ngrok tunnel to port 8081
public_url = ngrok.connect(8081)
print("\n" + "="*60)
print(f"[SUCCESS] AutoGen Studio is running!")
print(f"Click the link below to open the UI:")
print(f"{public_url}")
print("="*60 + "\n")

import os
import asyncio
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import MaxMessageTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient

async def run_team():
 # Fetch the Groq API key you securely entered in Cell 2
 groq_key = os.environ["GROQ_API_KEY"]

 # Define Groq model clients with the correct model_info settings
 researcher_model = OpenAIChatCompletionClient(
 model="llama-3.1-8b-instant",
 base_url="https://api.groq.com/openai/v1",
 api_key=groq_key,
 model_info={
 "vision": False,
 "function_calling": True,
 "json_output": True,
 "structured_output": True,
 "family": "unknown"
 }
 )

 editor_model = OpenAIChatCompletionClient(
 model="llama-3.3-70b-versatile",
 base_url="https://api.groq.com/openai/v1",
 api_key=groq_key,
 model_info={
 "vision": False,
 "function_calling": True,
 "json_output": True,
 "structured_output": True,
 "family": "unknown"
 }
 )

 # Define the individual Agents
 researcher = AssistantAgent(
 name="Researcher",
 model_client=researcher_model,
 system_message="You are an expert researcher. Provide a highly detailed summary using clear Markdown formatting."
 )

 editor = AssistantAgent(
 name="Editor",
 model_client=editor_model,
 system_message="You are a strict editor. Critique the researcher's work and optimize it for professional delivery."
 )

 # Orchestrate the workflow team
 team = RoundRobinGroupChat(
 participants=[researcher, editor],
 termination_condition=MaxMessageTermination(max_messages=4)
 )

 # Run the prompt
 print("--- Starting Multi-Agent Session ---")
 async for message in team.run_stream(task="Explain why Groq LPUs provide higher throughput for LLMs than standard GPUs."):
    if hasattr(message, "source") and hasattr(message, "content"):
        print(f"\n\033[1m[{message.source}]\033[0m: {message.content}")
        print("-" * 40)
    else:
        print("\n--- Final Result ---")
        print(message)
        print("-" * 40)

# Execute the async loop inside Google Colab

# Execute the async loop inside Google Colab
await run_team()

"""##Extension 1: Add a Tool-Wielding Agent

###Step 1: Create a Python Tool
"""

from typing import Annotated

def calculator(
    a: Annotated[float, "First number"],
    b: Annotated[float, "Second number"],
    operation: Annotated[str, "add, subtract, multiply, divide"]
) -> str:

    if operation == "add":
        return str(a + b)

    elif operation == "subtract":
        return str(a - b)

    elif operation == "multiply":
        return str(a * b)

    elif operation == "divide":
        if b == 0:
            return "Division by zero not allowed"
        return str(a / b)

    return "Invalid operation"

"""###Step 2: Create Tool Model"""

from typing import Annotated

def calculator(
    a: Annotated[float, "First number"],
    b: Annotated[float, "Second number"],
    operation: Annotated[str, "add, subtract, multiply, divide"]
) -> str:

    if operation == "add":
        return str(a + b)

    elif operation == "subtract":
        return str(a - b)

    elif operation == "multiply":
        return str(a * b)

    elif operation == "divide":
        if b == 0:
            return "Division by zero not allowed"
        return str(a / b)

    return "Invalid operation"

tool_model = OpenAIChatCompletionClient(
    model="llama-3.3-70b-versatile",
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ["GROQ_API_KEY"],
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "structured_output": True,
        "family": "unknown"
    }
)

"""### Step 3: Create Tool Agent"""

tool_agent = AssistantAgent(
    name="ToolAgent",
    model_client=tool_model,
    tools=[calculator],
    system_message="""
    You are a tool-enabled assistant.

    Whenever a mathematical calculation is required,
    use the calculator tool.

    Never perform calculations manually.
    Always call the tool.
    """
)

"""### Step 4: Update Team"""

groq_key = os.environ["GROQ_API_KEY"]

researcher_model = OpenAIChatCompletionClient(
    model="llama-3.1-8b-instant",
    base_url="https://api.groq.com/openai/v1",
    api_key=groq_key,
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "structured_output": True,
        "family": "unknown"
    }
)

editor_model = OpenAIChatCompletionClient(
    model="llama-3.3-70b-versatile",
    base_url="https://api.groq.com/openai/v1",
    api_key=groq_key,
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "structured_output": True,
        "family": "unknown"
    }
)

from typing import Annotated

def calculator(
    a: Annotated[float, "First number"],
    b: Annotated[float, "Second number"],
    operation: Annotated[str, "add, subtract, multiply, divide"]
) -> str:

    if operation == "add":
        return str(a + b)

    elif operation == "subtract":
        return str(a - b)

    elif operation == "multiply":
        return str(a * b)

    elif operation == "divide":
        return str(a / b) if b != 0 else "Division by zero"

    return "Invalid operation"

researcher = AssistantAgent(
    name="Researcher",
    model_client=researcher_model,
    system_message="""
    You are a research specialist.
    Gather information and identify calculations needed.
    """
)

tool_agent = AssistantAgent(
    name="ToolAgent",
    model_client=editor_model,
    tools=[calculator],
    system_message="""
    You are a tool-enabled assistant.

    Always use the calculator tool when calculations are required.

    Never calculate manually.
    """
)

editor = AssistantAgent(
    name="Editor",
    model_client=editor_model,
    system_message="""
    You are an editor.
    Produce the final polished response.
    """
)

team = RoundRobinGroupChat(
    participants=[
        researcher,
        tool_agent,
        editor
    ],
    termination_condition=MaxMessageTermination(max_messages=6)
)

"""### Step-5 Test"""

from autogen_agentchat.ui import Console

async def run_team():

    await Console(
        team.run_stream(
            task="""
            Calculate 125 * 48.
            Use the calculator tool.
            Explain the result.
            """
        )
    )
await run_team()
print(researcher)
print(tool_agent)
print(editor)
print(team)

"""## Extension 2: Add User Proxy Constraint

### Step 1: Create User Proxy Agent
"""

from autogen_agentchat.agents import UserProxyAgent

user_proxy = UserProxyAgent(
    name="user_proxy"
)

"""### Step 2: Update Team"""

team = RoundRobinGroupChat(
    participants=[
        researcher,
        editor,
        user_proxy
    ],
    termination_condition=MaxMessageTermination(max_messages=6)
)

"""### Step 3: Enable Human Approval

## Overview

The User Proxy Agent introduces a Human-in-the-Loop (HITL) validation step before the workflow is completed. This ensures that the generated response is reviewed and approved by a user before being delivered as the final output.

## Workflow

```text
User Query
    ↓
Researcher Agent
    ↓
Editor Agent
    ↓
User Proxy Agent
    ↓
Final Approved Response
```

## Approval Process

When the workflow reaches the User Proxy Agent, execution pauses and waits for user input.

The user can perform one of the following actions:

### 1. Approve Response

The generated output is accepted without changes.

Example:

```text
Approved
```

### 2. Request Modifications

The user provides feedback and requests changes.

Example:

```text
Please add recent OpenAI developments.
```

### 3. Reject Response

The response is rejected and agents are required to regenerate or improve the output.

Example:

```text
The report is incomplete. Please provide more technical details.
```

## Example Execution

### User Request

```text
Generate a report on Generative AI Trends.
```

### Workflow Execution

```text
Researcher Agent
    ↓
Collects information and prepares findings

Editor Agent
    ↓
Refines and structures the report

User Proxy Agent
    ↓
Requests user approval
```

### User Feedback

```text
Add a section on Agentic AI and Multi-Agent Systems.
```

### Updated Workflow

The feedback is incorporated and the workflow continues until approval is received.

## Benefits

* Enables Human-in-the-Loop validation
* Improves response quality and accuracy
* Reduces hallucinations
* Ensures business and compliance review before delivery
* Provides a controlled approval mechanism for enterprise workflows
"""

